### ISSUE TITLE
Problems compiling Raspberry PI 2

### ISSUE THREAD

**Issue by hespanha** [muggot/openmcu#8]
I tried to compile the openmcu in a Raspberry PI 2 (ARM7 processor) and I can go pretty far. However, eventually I get the error included below. Apparently, the assembly instruction 'pause' is being included in the compilation of video.cxx and it does not exist in ARM processors. I'm puzzled because I could not find any inline assembly anywhere. BTW, I am getting the following warning in 'configure'

$ ./configure
...
configure: WARNING: "CPU armv7l not recognized - proceed with caution!"
configure: OSTYPE set to linux
configure: OSRELEASE set to "3.18.0-trunk-rpi2"
configure: MACHTYPE set to armv7l
...

$ make
...
make[1]: Entering directory '/home/pi/RaspberryPi/telepresence/openMCU-ru/openmcu/openmcu-ru'
[CC] obj/main.o
[CC] obj/video.o
video.cxx: In member function ‘virtual BOOL TestVideoMixer::AddVideoSource(ConferenceMemberId, ConferenceMember&)’:
video.cxx:1780:19: warning: variable ‘o’ set but not used [-Wunused-but-set-variable]
video.cxx: In member function ‘virtual void TestVideoMixer::MyChangeLayout(unsigned int)’:
video.cxx:1820:19: warning: variable ‘o’ set but not used [-Wunused-but-set-variable]
/tmp/ccISdYAV.s: Assembler messages:
/tmp/ccISdYAV.s:30568: Error: bad instruction `pause'
/tmp/ccISdYAV.s:38891: Error: bad instruction`pause'
/tmp/ccISdYAV.s:42873: Error: bad instruction `pause'
/tmp/ccISdYAV.s:46336: Error: bad instruction`pause'
Makefile:59: recipe for target 'obj/video.o' failed
make[1]: **\* [obj/video.o] Error 1

**Comment by shf1325913748** [comment]
How to fix this bug？？
